goalObj (Goal Information-Collected 1 1)
goalMet True
(demands ((demand affiliation 0.9375) (demand competence 0.95) (demand energy 0.95)))
(modulators ((modulator positive-valence 0.5) (modulator goal-directedness 0.5) (modulator resolution-level 0.5) (modulator arousal 0.8351277524149181) (modulator securing-threshold 0.7549149868676283) (modulator selection-threshold 0.8769495921390369)))
(initiate-dialogue gather-information)
