(demands ((demand affiliation 0.9375) (demand competence 0.9) (demand energy 0.95)))
(modulators ((modulator positive-valence 0.5) (modulator goal-directedness 0.5) (modulator resolution-level 0.5) (modulator arousal 0.8335105319854276) (modulator securing-threshold 0.7549149868676283) (modulator selection-threshold 0.8664079614808038)))
(initiate-dialogue gather-information analyze-data summarize-findings compile-report deliver-results self-reflect)
