name: metta-run CI

on:
  push:
    branches:
      - main
      - experimental
  pull_request:
    branches:
      - main
      - experimental

jobs:
  setup-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.6"

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip==23.1.2
          pip install numpy==2.2.1
          python -m pip install hyperon==0.2.3
          metta --version

      - name: Run tests
        working-directory: ./
        run: |
          git submodule update --init --recursive
          mv utilities-module/utils-test.metta utilities-module/utilsTest.metta
          python3 test/run-tests.py
